dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    rooms:
      secure: JuJjwGMUQnToisMri0uuVis7j6KNPHvep9fEnh6JvDIXr52rmkfly2pI8huI/96VALnguZQM962DZugqVxSBSV2/OGzE8/fU8XSYMvfaWyDrW8j9BOVPWXObku1kCqa20qoGw27Dx6riXcG5FeKwthgas6GYe8cASuBdQsi+apYCc9R+BnfSnxW9xNgaS5EHjLw1WbTBRD7TpX47J8NHb40v3UFxh8qRMjKm79MPkge/D3jeGTmM3+LmJZwvKfIQR8ZURNR0yhj5L2OvanLG3SWtWt/Fef39eSVb+Ye5NSr4bDp7GO6GwvM5vCfHxsuRSl2neak7+f1TJrNjmOsTsQIx4PNBSI83N/Era3uixs/yC1sWAhBSD3ZVBAKKkU4h8MqMdqO1wdil0hdSj8ftDZP00m85OzTwjZ9h1phATnE3yCwB1Y9cuNAvqnqVYTGZSuAl5LvjJWBg9x2jN4hM57994NEEoQDkTOwplQ0RSW74/2M7Vd7ev5ZytszLno90sfqFzaDkQ3ttomJPoBw1tYUJ1g6QEBLx1PrL1bVEhw7t9gKhPjNtuyzOYOzQVnYn6IOolfKee5XvyT0F2P4IbIN1LCTL2hzO1F+RifWBLodt28TJP18WbO2nRapwPJZ0ETqixfbyyRCuc/8YHYAWP/Ewz1o8LXhqiQ2RwO+JhQU=
